#!/bin/bash
#BSUB -J test
#BSUB -o test_%J.out
#BSUB -q hpcintrogpu
##BSUB -B
##BSUB -N
#BSUB -n 32
#BSUB -R "rusage[mem=2048]"
#BSUB -W 15
#BSUB -R "span[hosts=1]"
#BSUB -gpu "num=1:mode=exclusive_process"

lscpu
lscpu -C

export MATMULT_RESULTS=0
export MATMULT_COMPARE=1
export MFLOPS_MAX_IT=1
export SIZES="1 73 175 373 453"
export NVCOMPILER_OMP_CUDA_GRID=165,13
export OMP_NUM_THREADS=13

echo "Start tests"

for m in $SIZES; do
  for n in $SIZES; do
    for k in $SIZES; do
      for type in mkn_omp lib lib_offload mkn_offload mnk_offload blk_offload; do
        output=$(./matmult_f.nvc++ $type $m $n $k)
        third_value=$(echo $output | awk '{print $3}')
        if [[ $third_value != 0 ]]; then
          echo "Warning: Non-zero third value ($third_value) $type $m $n $k"
        fi
      done
    done
  done
  echo "$type: $m"
done

for m in $(seq 2 80 500); do
  for n in $SIZES; do
    for k in $SIZES; do
      output=$(./matmult_f.nvc++ asy_offload $m $n $k)
      third_value=$(echo $output | awk '{print $3}')
      if [[ $third_value != 0 ]]; then
        echo "Warning: Non-zero third value ($third_value) asy_offload $m $n $k"
      fi
    done
  done
  echo "asy_offload: $m"
done

echo "End of test!"

exit 0;