#!/bin/bash
#BSUB -J test
#BSUB -o test_%J.out
#BSUB -q hpcintrogpu
##BSUB -B
##BSUB -N
#BSUB -n 32
#BSUB -R "rusage[mem=2048]"
#BSUB -W 15
#BSUB -R "span[hosts=1]"
#BSUB -gpu "num=1:mode=exclusive_process"

lscpu
lscpu -C

export MATMULT_RESULTS=0
export MATMULT_COMPARE=1
export MFLOPS_MAX_IT=1
export STEP=73
export NVCOMPILER_OMP_CUDA_GRID=165,13
export OMP_NUM_THREADS=13

echo "Start tests"

for m in $(seq 1 $STEP 1000); do
  for n in $(seq 1 $STEP 1000); do
    for k in $(seq 1 $STEP 1000); do
      for type in mkn_omp lib lib_offload mkn_offload mnk_offload blk_offload; do
        output=$(./matmult_f.nvc++ $type $m $n $k)
        third_value=$(echo $output | awk '{print $3}')
        if [[ $third_value != 0 ]]; then
          echo "Warning: Non-zero third value ($third_value) $type $m $n $k"
        fi
      done
    done
  done
  echo "$type: $m"
done

echo "End of test!"

# TODO asy_offload

exit 0;