#!/bin/bash
#BSUB -J test
#BSUB -o test_%J.out
#BSUB -q hpcintro
#BSUB -B
#BSUB -N
#BSUB -n 1
#BSUB -R "rusage[mem=2048]"
#BSUB -W 60

lscpu
lscpu -C

export MATMULT_RESULTS=0
export MATMULT_COMPARE=1
export MFLOPS_MAX_IT=1
export STEP=70

echo "Start tests"

for m in $(seq 1 $STEP 500); do
  for n in $(seq 1 $STEP 500); do
    for k in $(seq 1 $STEP 500); do
      for bs in $(seq 1 $STEP 500); do
        output=$(./matmult_f.gcc blk $m $n $k $bs)
        third_value=$(echo $output | awk '{print $3}')

        if [[ $third_value != 0 ]]; then
          echo "Warning: Non-zero third value ($third_value) for parameters m=$m, n=$n, k=$k, bs=$bs"
        fi
      done
    done
  done
  echo "blk: $m"
done

echo "End of blk!"

for type in lib nat mnk mkn nmk nkm kmn knm; do
  for m in $(seq 1 $STEP 500); do
    for n in $(seq 1 $STEP 500); do
      for k in $(seq 1 $STEP 500); do
        output=$(./matmult_f.gcc $type $m $n $k)
        third_value=$(echo $output | awk '{print $3}')

        if [[ $third_value != 0 ]]; then
          echo "Warning: Non-zero third value ($third_value) for type=$type, m=$m, n=$n, k=$k"
        fi
      done
    done
    echo "$type: $m"
  done
  echo "End of $type!"
done

echo "End of test!"

exit 0;